### ISSUE TITLE
Not loading in?

### ISSUE THREAD

**Issue by Gdogtheman** [cmdrads/RussianOrbiter#2]
I put this into the game data folder and nothing is showing up for the reskins, and no parts are showing up. Are there any more mods i need?

**Comment by cmdrads** [comment]
SOCK itself is obviously a dependency, it's good to also have Sock Repainted and Recoloured installed too.

If you have all of those and its still not working then you have simply installed it wrong

**Comment by Gdogtheman** [comment]
I got it from git hub and clicked game data and put Russianorbiter into game data i have sock, Sock Repainted and Recolored so is there something i did wrong?

**Comment by cmdrads** [comment]
you must have dragged the wrong folders into the wrong locations

I have just tested it now on a clean install and it works fine

make sure the folders inside the "RussianOrbiter" are Textures and Patches
